- name: Install nodejs and configure backend
  hosts: backend
  connection: ssh 
  become: yes
  tasks:
    - name: Install nodejs
      ansible.builtin.package:
        name: nodejs
        version: 20
        state: present
