- name: Install nodejs and configure backend
  hosts: backend
  connection: ssh 
  become: yes
  tasks:
    - name: Disabling nodejs
      ansible.builtin.command: "dnf module disable nodejs -y"
    
    - name: Enabling nodejs
      ansible.builtin.command: "dnf module enable nodejs:20 -y"
    
    - name: Install nodejs
      ansible.builtin.package:
        name: nodejs
        state: present
