- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
    - name: Install mysql libraries 
      ansible.builtin.pip:
        name: PyMySQL
        executable: pip3.9

    - name: Install mysql
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: Start and enable the service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Setup the root password if not Setup
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1 
        login_host: 98.84.107.230 #mysql public ip
      register: mysql_info
      ignore_errors: true

    - name: print the output
      debug:
        msg: " {{ mysql_info }}"