#!/bin/bash

echo " Please enter your username: "
read USERNAME # USERNAME is varaible 
# read is used for prompting data while executing the script

echo " Username is: $USERNAME "

echo "Enter your password: "
read -s PASS # -s is used when the user doesn't want to see the data what is being typed
echo "password saved successfully"
