- name: Install packages using loop
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Install all the packages mentioned in loop
    # debug:
    #   msg: "Installing {{ item }}"
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - git
    - tree
    - maven
    - nginx