- name: create ec2 instances via yaml script
  hosts: local
  connection: local
  vars:
    image_id: ami-09c813fb71547fc4f
    security_group: sg-0d58f7028d69e687e
    subnet_id: subnet-09b4eb336a24f31a4
    instances:
    - mysql 
    - frontend
    - backend
    instance_type: t3.micro

  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      image_id: "{{ image_id }}"
      security_group: "{{ security_group }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
      